name: Build and Deploy
on:
  push:
    branches:
      - Test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run deploydemo

    - name: List dist folder contents
      run: ls -la dist/SitoDeiSitiInsitoFE/browser

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: dist/SitoDeiSitiInsitoFE/browser
